services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notifications"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Notification Service
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8080:8080"
    environment:
      # Database Configuration (PostgreSQL)
      DATABASE_URL: postgres://notification_user:notification_password@postgres:5432/notifications?sslmode=disable
      
      # Email Configuration - Set these for real emails
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USERNAME: ${EMAIL_USERNAME:-}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-}
      
      # Slack Configuration - Set these for real Slack
      SLACK_TOKEN: ${SLACK_TOKEN:-}
      SLACK_CHANNEL: ${SLACK_CHANNEL:-#general}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      
      # Environment
      ENVIRONMENT: ${ENVIRONMENT:-development}
      
      # Server Configuration
      PORT: 8080
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MailHog for email testing (optional - only if you want to test emails locally)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped
    profiles:
      - testing  # Only start when using --profile testing

volumes:
  postgres_data: 